Update Pylint check to use pure bash solution

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,17 +36,12 @@ jobs:
     - name: Run Linter (pylint)
       shell: bash
       run: |
-        if [ "$RUNNER_OS" == "Windows" ]; then
-          pylint_output=$(pylint src/msftoolbox --exit-zero --output-format=text)
-          pylint_score=$(echo "$pylint_output" | grep -oP "Your code has been rated at \K[0-9.]+")
-          echo "Pylint score: $pylint_score"
-          if (( $(echo "$pylint_score < 6" | bc -l) )); then exit 1; fi
-        else
-          pylint src/msftoolbox || ( \
-          pylint_exit_code=$?; \
-          pylint_score=$(pylint src/msftoolbox --exit-zero --output-format=text | grep -o "Your code has been rated at .*" | awk '{print $7}' | awk -F '/' '{print $1}'); \
-          echo "Pylint score: $pylint_score"; \
-          if (( $(echo "$pylint_score < 6" | bc -l) )); then exit $pylint_exit_code; fi )
+        pylint_output=$(pylint src/msftoolbox --exit-zero --output-format=text)
+        pylint_score=$(echo "$pylint_output" | sed -n 's/.*rated at \([0-9.]*\).*/\1/p')
+        echo "Pylint score: $pylint_score"
+        if (( $(echo "$pylint_score < 6" | awk '{print ($1 < 6)}') )); then
+          echo "Pylint score is below 6. Failing the build."
+          exit 1
         fi
     - name: Run Tests with pytest and Coverage
       run: |
